### ISSUE TITLE
Thermal compensation of the measurement

### ISSUE THREAD

**Issue by PiotrBeeScale** [HannesOberreiter/bScale#7]
The temperature influences the balance indications. When the temperature changes, the weight reading changes, even though the load on the scale has not changed. 
Therefore, temperature measurement and balance reading compensation are required. 
![Pełzanie wagi1](https://user-images.githubusercontent.com/61093163/106257956-86cbaa00-621d-11eb-879f-fb5906ec38ec.jpg)
Need to install a temperature sensor. I chose SHTC3. 
![SHTC3-PODŁĄCZENIE](https://user-images.githubusercontent.com/61093163/106258642-64865c00-621e-11eb-819d-8c38b77c3b51.jpg)
Library:
https://www.14core.com/wiring-sensirion-i2c-shwx-shtcx-sht3x-temperature-humidity-sensor/

![Montaż SHTC3](https://user-images.githubusercontent.com/61093163/106258850-b5965000-621e-11eb-9407-6c138521a283.jpg)
![IMG_20201110_113741](https://user-images.githubusercontent.com/61093163/106258914-ce9f0100-621e-11eb-9c74-9f04c8b0bf93.jpg)
![SHTC3 kabelki i tasma](https://user-images.githubusercontent.com/61093163/106258953-dd85b380-621e-11eb-845b-e966f89296a3.jpg)

**Wiring sketch**
![Rysunek montażowy elementów i SIM800 - solar charger SHTC3](https://user-images.githubusercontent.com/61093163/106260224-72d57780-6220-11eb-9e2f-9ad45aee59e3.jpg)

The comparison of the temperature and weight measurements shows that the correction is possible with a linear function y=ax+b.
Here is an excel sheet with measurements and a calculated correction. 
[Kompensacja temperaturowa.xlsx](https://github.com/HannesOberreiter/bScale/files/5893111/Kompensacja.temperaturowa.xlsx)
**Arduino code changes :**

[Arduino_SHTC3.zip](https://github.com/HannesOberreiter/bScale/files/5893196/Arduino_SHTC3.zip)

**Comment by HannesOberreiter** [comment]
Hi Piotr,

hope you are doing well. Added the information for your new setup to the repo. I leave the Issue open for others to look at. 

I stopped working with hive scales, but I'm happy to see that you still work with it. 

Cheers
Hannes

**Comment by PiotrBeeScale** [comment]
Hello Hannes

I have noticed that you are tackling more serious projects. I am continuing to work on the scale as it has attracted interest on the beekeeping forum. By the way, there was a problem with the effect of temperature on the scale readings. The differences were so significant that a correction had to be worked out. I am pleased that new people have joined the topic. I hope that they will actively participate in the development of this project, the design of which has impressed me. Especially because of the power saving by using ATtiny85. An app for Android and iOS would be useful for this scale.  

 Wishing you good health and further success
Piotr

**Comment by HannesOberreiter** [comment]
Hello Piotr,

thats good to hear. Yes, scale drift by temperature is often overlooked even in professional sold bee hive scales. 

I reduced the amount of colonies, as the last few years I had a really bad harvest (2x lots of melezitose honey). Now I only do beekeeping as hobby anymore and try to find other ways to get some income for living. 

As for the App I'm working on making my application open source (rewriting code and remove external proprietary licences). This may help other beekeepers to host their own server and application in combination in combination with their own hive scale, but this project will take at least another year time, as I only can work on it on my free time.

Cheers
Hannes

**Comment by PiotrBeeScale** [comment]
Hello Hannes,
It is sad when there are losses in bees due to unfavorable natural conditions.
But seeing how well you write programs, I believe you have no trouble finding a job.
I am not a programmer, I dealt a bit with database administration. I also have a bit of an idea about electronics. Currently, I am developing scripts that analyze data from beekeeping scales so that event notifications are sent to gmail.
I am very glad that you are planning to provide a smartphone application.
Cheers
Piotr
