### ISSUE TITLE
saving the measurement for shipment 

### ISSUE THREAD

**Issue by Viator325** [HannesOberreiter/bScale#8]
Its possible to change the cod to:
-do a measurement of weight, temperature itp. on indicated time np. 6 AM and 6PM remeber this score and send one sms with this score on 8 PM ?
What about use RTC time for ardino ?

**Comment by HannesOberreiter** [comment]
Hi @Viator325,

as the attiny is the "timer" in this build, it is probably a little bit more difficult to get an exact timing. You could wake up the arduino more often and check a connected RTC timer - if the time is not ready go back to the attiny for the next cycle. Maybe you could rewrite the attiny  and use the attiny as RTC but I'm not sure if it is possible and how accurate the timer would be. 

You can change the code to anything you want, but I cannot give you support, as I'm not actively using any hive scales anymore. 

Closing this issue as it is a question and not and direct issue. 

Cheers
Hannes
